# Generated by Django 3.1.4 on 2020-12-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status post ', 'verbose_name_plural': 'Status posts'},
        ),
    ]
